In [2]:
import numpy as np

In [6]:
print(np.add(1.0, 4.0))



5.0


In [7]:
x1=np.arange(9.0).reshape((3, 3))
print(x1)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [8]:
x2=np.arange(3.0)
print(x2)

[0. 1. 2.]


In [9]:
x3=x1+x2
print(x3)

[[ 0.  2.  4.]
 [ 3.  5.  7.]
 [ 6.  8. 10.]]


In [18]:
x4=np.arange(3).reshape((3, 1))
print(x4)

[[0]
 [1]
 [2]]


In [17]:
x5=np.arange(9).reshape((3, 3))
print(x5)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
x6=x4+x5
print(x6)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


In [22]:
a=np.arange(9).reshape(3, 3)
print(a)
b=np.arange(1, 4)
print(b)
print(a/b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[1 2 3]
[[0.         0.5        0.66666667]
 [3.         2.         1.66666667]
 [6.         3.5        2.66666667]]


In [23]:
x11=np.arange(9.0).reshape((3, 3))
x12=2*np.ones(3)
print(x11/x12)

[[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]]


In [24]:
x13=np.arange(6)
np.power(x13, 3)


array([  0,   1,   8,  27,  64, 125], dtype=int32)

In [25]:
x14=[1.0, 2.0, 3.0, 3.0, 2.0, 1.0]
np.power(x13, x14)

array([ 0.,  1.,  8., 27., 16.,  5.])

In [26]:
x15=np.array([1, 2, 3, 3, 2, 1])
x16=np.arange(6)
x15**x16

array([ 1,  2,  9, 27, 16,  1])