In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("E:\movie imdb\ecommerceDataset.csv",names=['category','text'])

<>:1: SyntaxWarning: invalid escape sequence '\m'
<>:1: SyntaxWarning: invalid escape sequence '\m'
C:\Users\ankit\AppData\Local\Temp\ipykernel_10188\3266250460.py:1: SyntaxWarning: invalid escape sequence '\m'
  df = pd.read_csv("E:\movie imdb\ecommerceDataset.csv",names=['category','text'])


In [4]:
df

category                                               text
0        Household  Paper Plane Design Framed Wall Hanging Motivat...
1        Household  SAF 'Floral' Framed Painting (Wood, 30 inch x ...
2        Household  SAF 'UV Textured Modern Art Print Framed' Pain...
3        Household  SAF Flower Print Framed Painting (Synthetic, 1...
4        Household  Incredible Gifts India Wooden Happy Birthday U...
...            ...                                                ...
50420  Electronics  Strontium MicroSD Class 10 8GB Memory Card (Bl...
50421  Electronics  CrossBeats Wave Waterproof Bluetooth Wireless ...
50422  Electronics  Karbonn Titanium Wind W4 (White) Karbonn Titan...
50423  Electronics  Samsung Guru FM Plus (SM-B110E/D, Black) Colou...
50424  Electronics                   Micromax Canvas Win W121 (White)

[50425 rows x 2 columns]

In [5]:
y=df['category']

In [6]:
x=df['text']

In [7]:
x.fillna('',inplace=True)

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=23)

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [10]:
tf=TfidfVectorizer()

In [11]:
x_train1=tf.fit_transform(x_train)

In [12]:
x_test1=tf.transform(x_test)

In [13]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()

In [14]:
model.fit(x_train1,y_train)

RandomForestClassifier()

In [15]:
y_pred=model.predict(x_test1)

In [16]:
from sklearn.metrics import classification_report,confusion_matrix

In [17]:
print(classification_report(y_test,y_pred))

                        precision    recall  f1-score   support

                 Books       0.98      0.97      0.97      2325
Clothing & Accessories       0.97      0.97      0.97      1713
           Electronics       0.98      0.94      0.96      2052
             Household       0.95      0.98      0.97      3995

              accuracy                           0.97     10085
             macro avg       0.97      0.96      0.97     10085
          weighted avg       0.97      0.97      0.97     10085



In [18]:
print(confusion_matrix(y_test,y_pred))

[[2244   13   15   53]
 [   7 1659    7   40]
 [  17   11 1927   97]
 [  22   19   22 3932]]


In [21]:
#input from user 
input_text=input("Enter the text to predict the category: ")
input_text=tf.transform([input_text])
pred=model.predict(input_text)
print("Predicted category:",pred[0])

Predicted category: Clothing & Accessories
