In [1]:
import numpy as np

In [2]:
arr=np.array([1, 2, 3, 4, 5])
(arr)

array([1, 2, 3, 4, 5])

In [3]:
(type(arr))

numpy.ndarray

In [4]:
arr=np.array((1, 2, 3, 4, 5))
(arr)

array([1, 2, 3, 4, 5])

In [5]:
arr=np.array(42)
(arr)

array(42)

In [6]:
arr=np.array([[1, 2, 3],[4, 5, 6]])
(arr)

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
(arr)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [9]:
(arr.ndim)

3

In [11]:
arr=np.array([1, 2, 3, 4, 5], ndmin=5)
(arr)
#(arr.ndim)

array([[[[[1, 2, 3, 4, 5]]]]])

In [14]:
(arr[0::])

array([[[[[1, 2, 3, 4, 5]]]]])

In [15]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [17]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


In [21]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[::, -3])

[3 8]


In [22]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [23]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [24]:
arr=np.array([1, 2, 3, 4, 5])
arr[0]=55
x=arr.copy()
(arr)
(x)

array([55,  2,  3,  4,  5])

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]
