In [1]:
import numpy as np

In [41]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [42]:
list = [1, 2, 3]
np_list = np.array(list)
print(np_list)

[1 2 3]


In [6]:
a = np.arange(2, 4)
print(a)

[2 3]


In [7]:
b = np.array([[2, 4]])
print(b)

[[2 4]]


In [8]:
c = np.array([[2], [4]])
print(c)

[[2]
 [4]]


In [13]:
d = np.arange(2, 6)
print(d)

[2 3 4 5]


In [26]:
e = np.random.randint((3, 5))
print(e)

[1 1]


In [18]:
e = np.random.rand(2, 3)
print(e)

[[0.42304733 0.20019068 0.91834918]
 [0.41581879 0.35517776 0.80322039]]


In [33]:
e = np.random.randint(3, 5, size=8)  # Generates an array of random integers between 3 (inclusive) and 5 (exclusive).
print(e)

[3 3 4 4 4 4 3 3]


In [37]:
import plotly.graph_objects as go

# Create a bar chart using the variables
fig = go.Figure()

fig.add_trace(go.Bar(x=list(range(len(a))), y=a, name='a'))
fig.add_trace(go.Bar(x=list(range(len(d))), y=d, name='d'))
fig.add_trace(go.Bar(x=list(range(len(e))), y=e, name='e'))
fig.add_trace(go.Bar(x=list(range(len(f))), y=f, name='f'))

# Update layout
fig.update_layout(
    title="Bar Chart of Variables",
    xaxis_title="Index",
    yaxis_title="Value",
    barmode='group'
)

# Show the figure
fig.show()