In [1]:
import numpy as np

In [3]:
a=np.empty(4)
print(a)

[2.12199579e-314 9.90972034e-312 7.11454530e-321 6.95250701e-310]


In [4]:
b=np.empty(5)
print(b)

[2.12199579e-314 9.90972034e-312 5.55329786e-321 6.95250701e-310
 1.62122831e-086]


In [5]:
np.random.rand(3)

array([0.73924187, 0.11160492, 0.71200924])

In [6]:
np.random.randint(4)

3

In [22]:
np.random.randint(5)

1

In [12]:
a=np.random.randint(8, 15, 4)
print(a)

[10 12 13  8]
